# Single replica, pinned to the node.
#
# For databases that replicate at the application layer - Postgres, Elasticsearch. 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  dataLocality: strict-local
  staleReplicaTimeout: "30"
  fsType: ext4
