apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-stg
  namespace: argocd
spec:
  project: app-stg
  source:
    repoURL: 'https://github.com/deployment/helm/app.git'
    targetRevision: HEAD
    path: deployment/helm/app
    helm:
      valueFiles:
        - environments/stg/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
