---
# defaults file for rke

# images_file: "rke2-images.linux-amd64.tar.gz"
# rke2_binary: "rke2.linux-amd64.tar.gz"
# sha_file: "sha256sum-amd64.txt"

rke2_artifacts:
  - rke2-images-calico.linux-amd64.tar.gz
  - rke2-images-core.linux-amd64.tar.gz
  - rke2.linux-amd64.tar.gz
  - rke2-images.linux-amd64.tar.gz
  - sha256sum-amd64.txt
  
rke_config_dir: "/etc/rancher/rke2"
rke_manifests_dir: "/var/lib/rancher/rke2/server/manifests"


images_dir: "/opt/images"
container_images: "container-images.tar.gz"

container_registry: ""
registry_username: ""
registry_password: ""

token: ""

kube_vip_tag: ""
kube_vip_dns: ""

