apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  labels:
    app: postgresql
  annotations:
    {{- if .Values.global.istio.enabled }}
    inject.istio.io/templates: "sidecar,spire"
    traffic.sidecar.istio.io/excludeInboundPorts: "8000,9187"
    {{- end }}
spec:
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  instances: {{ .Values.postgresql.instances }}
  imageName: {{ .Values.postgresql.image }}
  storage:
    size: {{ .Values.postgresql.storage.size }}
    storageClassName: {{ .Values.postgresql.storage.Class }}
  resources:
    requests:
      memory: {{ .Values.postgresql.resources.requests.memory }}
      cpu: {{ .Values.postgresql.resources.requests.cpu }}
    limits:
      memory: {{ .Values.postgresql.resources.limits.memory }}
      cpu: {{ .Values.postgresql.resources.limits.cpu }}
